### ISSUE TITLE
Question about inference process

### ISSUE THREAD

**Issue by kimwongyuda** [qcwthu/Lifelong-Fewshot-Language-Learning#1]
In the paper, there is a sentence which talk about limitation of manual prompt, "Furthermore, the manual design assumes knowing the task in advance, which limits its applicability to lifelong learning where the next task to learn may not be known in advance.".

However, the model takes a task-specific generation token as input, which can give information about the next task to the model. Is it also kind of above limitation?

Also, apart from above question, when the model inferences with respect to certain domain of certain task, does the model take the task-specific generation token corresponding to the domain as input?

**Comment by qcwthu** [comment]
Hi, sorry for the late reply. The task-specific generation token is for current task, not for next task. You can not know it in advance!
For your next question, No. All domains of the same type share the same generation token.
